version: 1.0

services:
  - name: frontend
    type: web
    env: node
    build:
      commands:
        - npm install
    start:
      command: serve -s .  # Serve static files (make sure to install `serve` or another static file server)
    routes:
      - type: rewrite
        source: /socket.io  # Forward socket.io requests to the backend
        destination: http://backend:3000/socket.io

  - name: backend
    type: web
    env: node
    build:
      commands:
        - npm install
    start:
      command: node server.js
    envVars:
      - key: CORS_ALLOWED_ORIGIN
        value: "*"
      - key: PORT
        value: 3000
    routes:
      - type: websocket
        source: /socket.io  # WebSocket route for socket.io
        destination: http://backend:3000/socket.io
