version: 1.0

services:
  - name: frontend
    type: web
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: .  # Ensures all static files (index.html, etc.) are served from the root directory
    routes:
      - type: rewrite
        source: /socket.io  # Rewrite path for Socket.io client script
        destination: http://backend:3000/socket.io  # Forward requests to backend

  - name: backend
    type: web
    env: node
    envVars:
      - key: CORS_ALLOWED_ORIGIN
        value: "*"
      - key: PORT
        value: 3000
    routes:
      - type: websocket
        source: /socket.io
        destination: http://backend:3000/socket.io
