version: 1.0

services:
  - name: web
    type: static  # Serves the frontend files
    env: static
    staticPublishPath: .  # Ensures index.html and all static files are served from the root directory
    build:
      commands:
        - npm install
    routes:
      - type: rewrite
        source: /socket.io  # Forward socket.io requests to the backend
        destination: http://api:3000/socket.io

  - name: api
    type: web  # Runs the backend server
    env: node
    build:
      commands:
        - npm install
    start:
      command: node server.js
    envVars:
      - key: CORS_ALLOWED_ORIGIN
        value: "*"
      - key: PORT
        value: 3000
    routes:
      - type: websocket
        source: /socket.io  # WebSocket route for socket.io
        destination: http://api:3000/socket.io
